Ft/#182215594 reject/approve request
atlp-rwanda/strikers-bn-be pull request #38
Opened 2022-06-08 18:26 UTC by kelliaUmuhire

#### What does this PR do?
Adds status update endpoint
#### Description of Task to be completed?
Endpoint `PUT /api/v1/trips/status/<request_id>`
#### How should this be manually tested?
* clone project and run `npm i`
* test endpoint `PUT /api/v1/trips/status/<request_id>`
#### What are the relevant pivotal tracker stories?
#182215594

2022-06-13 19:24 UTC, MikeManzi approved these changes

2022-06-14 18:27 UTC, IgihozoColombe approved these changes

2022-06-21 05:20 UTC, IgihozoColombe approved these changes

2022-06-21 05:22 UTC, IgihozoColombe reviewed
Should not have conflicts with develop

2022-06-22 09:58 UTC, kelliaUmuhire commented
The conflicts with main are resolved

2022-08-11 08:14 UTC, leny62 requested changes
@kelliaUmuhire , please update your tests, check on develop.
The total number of tests should be around 66

2022-08-12 13:26 UTC, merged