feat(182215592): users trip request
atlp-rwanda/strikers-bn-be pull request #43
Opened 2022-06-09 17:21 UTC by IgihozoColombe

2022-06-10 20:11 UTC, IsiteYves approved these changes

2022-06-11 07:00 UTC, IsiteYves requested changes
Try to use the correct API naming convention.For Endpoint GET `/api/v1/trips/all`, it should  have been GET `/api/v1/trips` only.

2022-06-11 07:02 UTC, IsiteYves reviewed
Try to use the suggested API naming convention.For endpoint GET `/api/v1/trips/all`, it should have been GET `/api/v1/trips` only

2022-06-12 17:16 UTC, NezaBruce approved these changes

2022-06-12 17:36 UTC, kelliaUmuhire approved these changes

2022-06-13 04:09 UTC, IsiteYves approved these changes

2022-06-13 17:57 UTC, leny62 approved these changes

2022-06-13 18:00 UTC, leny62 commented
@IgihozoColombe , check the circle-ci build and test issue

2022-06-13 18:01 UTC, leny62 commented
@IgihozoColombe , check the circle-ci build and test issue

2022-06-13 18:01 UTC, leny62 commented
@IgihozoColombe , check the circle-ci build and test issue

2022-06-13 18:39 UTC, kelliaUmuhire approved these changes

2022-06-13 18:53 UTC, pmuhire approved these changes

2022-06-16 08:58 UTC, leny62 requested changes
Good progress @IgihozoColombe , comply to the requested changes of changing to ES6 and also Rebase!

2022-06-16 08:58 UTC, leny62 commented on models/index.js
> +const path = require('path');
Please use ES6

2022-06-16 08:58 UTC, leny62 commented on src/models/index.js
>  const Sequelize = require('sequelize');
Please use ES6

2022-06-16 08:58 UTC, leny62 commented on src/models/triprequest.js
> +const {
Please use ES6

2022-06-16 16:54 UTC, closed without merging