Ft users should be able to book a room in accomodationfacility 182215595
atlp-rwanda/strikers-bn-be pull request #47
Opened 2022-06-14 19:36 UTC by IsiteYves

#### What does this PR do?

- Checks out to 2 branches

#### Description of Task to be completed?

- Checks out to (goes into update with) 2 branches (`chore/#182215585-user-role-settings` and `ft-travel-admins-should-be-able-to-CRUD-accommodation-facilities-182215591`)

#### How should this be manually tested?

- Clone the repo

- checkout to branch `chore/#182215585-user-role-settings`

- Run `npm install` to install dependencies

- Run `npm run test` to run tests

- Run `npm run test`

- Run `npm run coverage`

#### Pivotal Tracker Story

- [Link to Pivotal Tracker Story](https://www.pivotaltracker.com/n/projects/2569362/stories/182215595)

2022-06-17 09:10 UTC, NezaBruce approved these changes

2022-06-17 15:51 UTC, leny62 requested changes
Some of the codes are still ES5, and also rebase to resolve conflicts with the base branch

2022-06-17 15:51 UTC, leny62 commented on models/index.js
> +
Kindly convert this code to ES6

2022-06-21 05:18 UTC, IgihozoColombe approved these changes

2022-06-21 20:49 UTC, leny62 requested changes
@IsiteYves , kindly resolve your conflicts

2022-06-23 14:19 UTC, leny62 approved these changes

2022-06-23 14:19 UTC, merged