[chore] set up docker compose for project
atlp-rwanda/strikers-bn-be pull request #5
Opened 2022-05-18 20:11 UTC by Peter-Mfitumukiza

#### What does this PR do?
- Configure docker-compose
#### Description of Task to be completed?
- Set up a ymal file that will run express server and postgress db using docker compose
#### How should this be manually tested?
- Clone the repo

- checkout to branch `chore/#182215581-setup-docker`

- Run `docker-compose up` to run the application using docker

2022-05-19 17:49 UTC, acele-happy approved these changes

2022-05-19 18:42 UTC, kelliaUmuhire reviewed
Reviewed

2022-05-19 19:49 UTC, leny62 requested changes
Rebase with the base branch!

2022-05-20 12:58 UTC, kelliaUmuhire approved these changes

2022-05-20 13:00 UTC, merged