Ft travel admins should be able to crud accommodation facilities 182215591
atlp-rwanda/strikers-bn-be pull request #52
Opened 2022-06-20 13:20 UTC by acele-happy

2022-06-20 16:59 UTC, MikeManzi reviewed
Try to add your latest commits to the pr

2022-06-21 07:08 UTC, NezaBruce approved these changes

2022-06-21 12:15 UTC, leny62 requested changes
Nice work @acele-happy , but it seems you rebased and there a lot of trailing lines that you haven't removed

2022-06-21 12:15 UTC, leny62 commented on coverage/lcov-report/src/controllers/index.html
> +<<<<<<< HEAD
Can you remove these trailing spaces please @acele-happy . Otherwise there will be many errors

2022-06-21 12:15 UTC, leny62 commented on coverage/lcov-report/src/controllers/user.controller.js.html
> +<<<<<<< HEAD
Also remove these trailing lines

2022-06-21 12:15 UTC, leny62 commented on coverage/lcov-report/src/controllers/user.controller.js.html
> +<<<<<<< HEAD
Remove the trailing line

2022-06-21 12:15 UTC, leny62 commented on coverage/lcov-report/src/models/index.js.html
> +<<<<<<< HEAD
Remove the trailing spaces

2022-06-21 12:15 UTC, leny62 commented on coverage/lcov-report/src/models/index.js.html
> +>>>>>>> 134818b6b88a23424d4933cf0c89b3999cf92e22
```suggestion

```

2022-06-21 12:15 UTC, leny62 commented on coverage/lcov-report/src/models/index.js.html
> +>>>>>>> 134818b6b88a23424d4933cf0c89b3999cf92e22
```suggestion
>>>>>>> 134818b6b88a23424d4933cf0c89b3999cf92e22
```

2022-06-21 18:41 UTC, leny62 approved these changes

2022-06-21 18:42 UTC, merged