Ft user oauth google and facebook
atlp-rwanda/strikers-bn-be pull request #58
Opened 2022-07-05 19:14 UTC by Graziee6

##What does this PR do?
create a new branch for user login by google oauth and facebook

ScreenshotsN/A

2022-07-18 19:05 UTC, kelliaUmuhire approved these changes
Well done!

2022-07-18 19:35 UTC, NezaBruce approved these changes

2022-07-20 07:42 UTC, denislohan requested changes
You need to write tests for your feature

2022-07-29 08:46 UTC, leny62 requested changes
@Graziee6 , your tests are not passing. And one of the reasons is the trailing spaces you haven't removed

2022-07-29 08:46 UTC, leny62 commented on .eslintrc.json
> +<<<<<<< HEAD
@Graziee6 please remove such trailing spaces

2022-07-29 08:46 UTC, leny62 commented on .eslintrc.json
> +=======
@Graziee6 , your files have trailing spaces

2022-08-08 23:12 UTC, leny62 commented
@Graziee6 , please rebase!

2022-09-04 16:30 UTC, leny62 approved these changes

2022-09-04 16:32 UTC, merged